language: node_js
node_js:
  - stable
  - 4
  - 3
  - 2
  - 1
  - 0.12
before_script:
  - sudo apt-get install build-essential libssl-dev git
  - git clone https://github.com/wg/wrk.git
  - cd wrk && make && sudo cp wrk /usr/local/bin && cd ..
script:
  - make test-travis
  - make bench
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov
